name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies with PNPM
        run: pnpm install --no-frozen-lockfile

      - name: Build the app
        run: pnpm run build
